In [ ]:
##iAAFT Surrogates 

In [2]:
import numpy as np
import nolds
from matplotlib import pyplot as plt
from numpy import linalg as la
import os
from scipy import stats
from scipy import spatial as sp
from scipy import sparse
from sklearn import linear_model
from scipy import linalg as sla

import lyapynov as le

import pandas as pd
import networkx as nx

import SystemsSolved as s
import Methods as m

import Sparse_Reservoir_Computing as rc

import RecurrencePlotsCode as rp


import multiprocess as mp

In [3]:
mu = 0.00; nu = 0.00
Ry = s.yCoupledRossler(a = 0.2, b = 0.2, c = 5.7, nu1 = nu, mu1 = mu, nu2 = nu, mu2 = mu)
Ry_ts = Ry.solve(t0 = 0, tFinal = 1000, x0_1 = [-1.5, 1.5, 20], x0_2 = [-1, -1, 10], dt = 0.01)

A0 = Ry_ts[0:3, :]; B0 = Ry_ts[3:6, :]

In [4]:
import iaaft

In [ ]:
Surrogates1 = iaaft.surrogates(A0[0, :].T, ns=100)
Surrogates2 = iaaft.surrogates(A0[1, :].T, ns=100)
Surrogates3 = iaaft.surrogates(A0[2, :].T, ns=100)

Estim  0%|                              | 0/100 [00:00<?, ?it/s]

Estim100%|██████████████████████████████| 100/100 [05:28<00:00,  3.28s/it]


In [17]:
Surrogates2 = iaaft.surrogates(A0[1, :].T, ns=100)
Surrogates3 = iaaft.surrogates(A0[2, :].T, ns=100)

Estim 20%|██████                        | 20/100 [33:37<2:14:29, 100.87s/it]


KeyboardInterrupt: 

In [ ]:
Surrogates[1, :]

(100000,)

In [11]:
#Setting time for real trajectories
tStart = 700
tEnd = 800
dt = 0.01
iStart = int(tStart/dt) #Discarding beginning of time series 
iEnd = int(tEnd/dt) 

In [13]:
params

[[array([-0.24322533, -0.16549233, -0.07107777, ..., -0.98662774,
         -0.90626636, -0.81987046]),
  array([[ 3.7232319 ,  3.72236257,  3.72111765, ...,  9.22753098,
           9.29960085,  9.37075677],
         [-0.01767957,  0.01955057,  0.05684467, ..., -7.55445331,
          -7.47684835, -7.39837115],
         [ 0.08585315,  0.08615271,  0.08644551, ...,  0.30229294,
           0.31529601,  0.32900562]])],
 [array([-3.0788884 , -3.14097086, -3.20826972, ..., -8.01638838,
         -8.05554276, -8.08650545]),
  array([[ 3.7232319 ,  3.72236257,  3.72111765, ...,  9.22753098,
           9.29960085,  9.37075677],
         [-0.01767957,  0.01955057,  0.05684467, ..., -7.55445331,
          -7.47684835, -7.39837115],
         [ 0.08585315,  0.08615271,  0.08644551, ...,  0.30229294,
           0.31529601,  0.32900562]])],
 [array([-6.9751202 , -7.01954174, -7.05526835, ..., -2.94905186,
         -2.97071076, -3.00379966]),
  array([[ 3.7232319 ,  3.72236257,  3.72111765, ...,  9.2275

array([[ 3.7232319 ,  3.72236257,  3.72111765, ...,  9.22753098,
         9.29960085,  9.37075677],
       [-0.01767957,  0.01955057,  0.05684467, ..., -7.55445331,
        -7.47684835, -7.39837115],
       [ 0.08585315,  0.08615271,  0.08644551, ...,  0.30229294,
         0.31529601,  0.32900562]])

In [16]:
params = []
for i in range(0, 100):
    a = [Surrogates[i, iStart:iEnd].tolist(), B0[0, iStart:iEnd]]
    params.append(a)

#Comute Statistics 
with mp.Pool(processes=6) as pool:
    results = pool.starmap_async(m.PSstat1, params)
    S_stats = results.get()

AttributeError: 'list' object has no attribute 'T'